### ISSUE TITLE
在vite开发环境添加了环境变量文件.env.vite_dev后，在app.vue里使用，如下, 但打包出错，如何隔开使用vue-cli4.X

### ISSUE THREAD

**Issue by wwb568109135** [lceric/vite-vue2-demo#2]
在app.vue里使用，如下：
 mounted() {
    

    console.log("window.axios  this.$api.get ================="+ new Date().getTime(),window.axios)

    // 环境变量   文档： https://www.pipipi.net/vite/guide/env-and-mode.html
    if( import &&  import.meta && import.meta.env.VITE_APP_URL ){
      console.log(import.meta)

      this.$api.get(import.meta.env.VITE_APP_URL +'test').then(res=>{
        console.log(res.data)

        setTimeout(()=>{
          this.ab = res.data;
        },1000)
        
      })
    }else{
      this.$api.get('jquery.js?new=pro')
    }
    
  }

打包出错了，npm run build：

$ npm run build

> viet2_vue2_elementUI@0.1.0 build F:\work\vite-vue2-demo
> vue-cli-service build

-  Building for production...
[
  {
    title: 'gitlab-Vite Vue2 Demo',
    templateParameters: [Function],
    minify: {
      removeComments: true,
      collapseWhitespace: true,
      collapseBooleanAttributes: true,
      removeScriptTypeAttributes: true
    },
    template: 'F:\\work\\vite-vue2-demo\\node_modules\\.tmp\\build\\index.html',
    filename: './index.html'
  }
]
 ERROR  Failed to compile with 1 error8:37:33 ├F10: PM┤

 error  in ./src/App.vue?vue&type=script&lang=js&

Syntax Error: Thread Loader (Worker 0)
F:\work\vite-vue2-demo\src\App.vue: import can only be used in import() or import.meta (44:8)

  42 |
  43 |     // 环境变量   文档： https://www.pipipi.net/vite/guide/env-and-mode.html
> 44 |     if( import &&  import.meta && import.meta.env.VITE_APP_URL ){
     |         ^
  45 |       console.log(import.meta)
  46 |
  47 |       this.$api.get(import.meta.env.VITE_APP_URL +'test').then(res=>{

 @ ./src/App.vue?vue&type=script&lang=js& 1:0-302 1:318-321 1:323-622 1:323-622
 @ ./src/App.vue
 @ ./src/main.js
 @ multi ./src/main.js

 ERROR  Build failed with errors.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! viet2_vue2_elementUI@0.1.0 build: `vue-cli-service build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the viet2_vue2_elementUI@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\wuwanbing\AppData\Roaming\npm-cache\_logs\2021-04-07T12_37_33_615Z-debug.log

**Comment by lceric** [comment]
思路：
  通过loader把vite特有的环境变量`import.mate.env.`在打包的时候修正为webpack的`process.env.`
  
  由于vue-cli在配置`.env.[env]`文件时，只会把`VUE_APP_`开头的变量通过`webpack.DefinePlugin`注入，`process.env.`使用，故webpack打包需要做一步注入变量

在demo里我这边做了个示例，你可以看一下：
```js
  configureWebpack: {
    module: {
      rules: [
        {
          test: /\.js$/,
          use: [
            {
              loader: 'raw-edit-loader',
              options: rawEditLoaderOptions(),
            },
          ],
        },
      ],
    },
    plugins: [new webpack.DefinePlugin(getViteEnvVarDefine())],
  },
```
