### ISSUE TITLE
为何我允许打包报错了呢

### ISSUE THREAD

**Issue by wzs28150** [lceric/vite-vue2-demo#5]
![image](https://user-images.githubusercontent.com/21290257/177899079-d5fda9f1-0aec-46be-bf8b-9c8b1e67307c.png)
我刚拉下来您的代码 打算试一下 dev时没什么问题 build失败了

**Comment by lceric** [comment]
halo，我这边lock了版本，你可以拉取最新代码试一下。最新代码我在win上，mac上做了build，没有出现这个问题。

**Comment by wzs28150** [comment]
> halo，我这边lock了版本，你可以拉取最新代码试一下。最新代码我在win上，mac上做了build，没有出现这个问题。
感谢`
